spring:
  application:
    name: BanckendKC
  datasource:
      url: jdbc:postgresql://localhost:5432/kamycarnes
      username: augalde
      password: 
    
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

server:
    port: 8080